### PR TITLE
PR#1

### PR DESCRIPTION
**Pull request by slavazhil**

### CODE REVIEW

**Comment by slavazhil** [comment]
Another limitation is that the server only supports commands that don't require another user input for it to finish. Othervise they will timeout.
For example: workerctl start "yum install golang"
Should be provided with the "-y" flag

**Comment by slavazhil** [comment]
The server will run in a docker container and the client will run on a local machine and connect through localhost.

**Comment by slavazhil** [comment]
@russjones @Joerger @quinqu

**Comment by wadells** [comment]
Hi @slavazhil!  Thanks for your interest.  This gereral careers repo isn't intended to be shared between different candidates.  Please create a new repo under your account and invite the relevant folks.  You're welcome to copy the challenge descriptions into it if you'd like a local copy.

Let me (or your interview team) know if you have questions.

**Pull request closed without merging**
