### PR TITLE
Add Security Engineer Levels

### PR DESCRIPTION
**Pull request by wadells**
## Context

This matrix will be used for three different roles on the Security team under @reedloden:

* Generalist https://jobs.lever.co/teleport/84617269-125e-46af-a71e-cbdce19a2dd9
* Application https://jobs.lever.co/teleport/d662de87-f884-4a2a-9d92-bc484bb8a9aa
* Cloud https://jobs.lever.co/teleport/66b315e5-363f-4ee8-91d3-cc446eecf598

As such, some parts of the matrix are intentionally general, as it is tough to get in to technology specifics in a focus agnostic way.

This matrix based heavily off the following:

* Teleport's long standing systems engineering levels: https://github.com/gravitational/careers/blob/7c5ae4161f6a2ac8ebe01f96f7bf24529414ed2e/levels/systems.pdf
* Dropbox's levels: https://dropbox.github.io/dbx-career-framework/ic2_security_engineer.html  These are well thought out, but *quite verbose*
* This [PDF](https://github.com/gravitational/careers/files/9366475/6838664664960418760sec-securityengineeringcareerladder-120722-1607.pdf) (I don't know where it comes from)
* Gitlab's levels https://about.gitlab.com/job-families/engineering/security-engineer/

## Feedback Questions

Some questions I'd like feedback on:

* Are the columns at the top appropriate?  I collapsed Datastructures/Algorithms/Networking/Systems/Tools/SRE into a general "Knowledge" column, as I found the specificity of detail in the systems matrix didn't map well to the three roles we're targeting.
* More importantly, are there columns that are missing?

Please leave any and all other feedback inline!

## Other Notes

This is based off of #68 / #72.  If those don't land first, I'll rebase off main to pick up the appropriate make changes.

### CODE REVIEW

**Comment by wadells** [comment]
Some feedback from @TravisGary in slack:

> on the topic tho, maybe another column for mentorship?
> I know IT one has expectations for helping with recruiting and mentoring others that kick in after a certain level
> also maybe a mention of SIEM, threat detection, static /dynamic analysis tools

He also provided the IT leveling matrix available on [google drive](also maybe a mention of SIEM, threat detection, static /dynamic analysis tools).

**Comment by reedloden** [comment]
This is great! Thanks so much for working on this.

I feel like Level 5 is lacking. The only real difference between L4 and L5 is a few projects vs. multiple projects affecting cross-company. Maybe that's enough, but it feels like some of the other columns could have some differences as well. Perhaps the new Mentorship column could include something additional?

**Comment by adaadb6** [comment]
Curious how the leveling would match to titles such as `senior`, `staff`, etc? Would the corresponding leveling (L4-5?) match our job descriptions for open staff positions?

**Comment by wadells** [comment]
> Curious how the leveling would match to titles such as `senior`, `staff`, etc? Would the corresponding leveling (L4-5?) match our job descriptions for open staff positions?

Good question.  We don't use Senior/Principle/Staff internally for our engineering levels, just L1-L6.  The "Staff" designation in the job descriptions is more of a marketing thing to help attract the right talent.  I don't know exactly how we'd map those L1-L6 to other companies.

Based on my institutional knowledge, it'd be something like;

L1 - Junior - Just of out college or equivalent skill
L2 - "Regular" - Some industry experience, still lots to learn.
L3 - Senior - Standard level for engineers, we don't "up our out" folks past this, they can hang out at this level.
L4 - Principle
L5 - Staff
L6 - You're Kelsey Hightower or Brad Fitzpatrick or something.  You could start your own company anyday but we're glad you're killing it at Teleport.

Unfortunately https://www.levels.fyi/?compare=Teleport,Google,Amazon&track=Software%20Engineer doesn't have enough info to give us a map yet.  It's probably the best source for comparing across employers once it has been trained.

**Comment by wadells** [comment]
> I feel like Level 5 is lacking. The only real difference between L4 and L5 is a few projects vs. multiple projects affecting cross-company. Maybe that's enough, but it feels like some of the other columns could have some differences as well. Perhaps the new Mentorship column could include something additional?

Part of the problem is I don't have the *security specific* knolwedge part of L4 vs L5 security engineer -- so I didn't know what to pencil in as appropriate differences for Security Knowledge or Threat Fluency. I'd probably consider myself L3 on the security track.

However I added more detail on mentorship in https://github.com/gravitational/careers/pull/73/commits/744570172d5c83e604ee7b2e983678b00bd949c3, and improved L3-L5 scope in https://github.com/gravitational/careers/pull/73/commits/3bb3d58c067b21c0942490470125ee53002e5fc6.

**Comment by reedloden** [comment]
> L1 - Junior - Just of out college or equivalent skill
> L2 - "Regular" - Some industry experience, still lots to learn.
> L3 - Senior - Standard level for engineers, we don't "up our out" folks past this, they can hang out at this level.
> L4 - Principle
> L5 - Staff
> L6 - You're Kelsey Hightower or Brad Fitzpatrick or something. You could start your own company anyday but we're glad you're killing it at Teleport.

Every company does it slightly differently, but generally, I see: Senior --> Staff --> Principal --> Distinguished.

**Comment by wadells** [comment]
cc @codingllama @nklaassen and @tobiaszheller for any feedback from the product security team (since you all are in an adjacent role)

**Review by reedloden — APPROVED** [review]
I think several things in L1 could probably be moved to L2. I'm skeptical that a fresh out of school junior security engineer would know all common attacks from OWASP Top 10, but perhaps I'm just jaded. Not sure it really matters right now, as we're not hiring L1 or L2.

Overall, this is great to have something use, and we can iterate as needed. Would love to hear some feedback from other engineering folks at Teleport just to make sure we're being consistent across different engineering roles, but not a blocker, imho.

**Comment by wadells** [comment]
> Would love to hear some feedback from other engineering folks at Teleport just to make sure we're being consistent across different engineering roles, but not a blocker, imho.

Since this is targeting `rjones/sre-levels`, I'll leave it open to gather further feedback.  In the meantime, I'll squash, rebase, and merge so we have something to point candidates at in the challenge doc and job description.

**Comment by wadells** [comment]
Without any further feedback -- I'm going to close this for now.  We can always revisit later.

**Pull request closed without merging**
