### PR TITLE
Switch remaining latex to markdown

### PR DESCRIPTION
**Pull request by wadells**
Latex is a relative pain to work with, and it'd be good to be done with it in this repo.

I didn't edit any of the levels content -- I reformatted it.  As such, I'd like to focus review on the format and organization and not the content.  I recognize the content could likely use a brush up, but that isn't the point of this PR.  We can loop back to that later.

Questions for reviewers:

1. Do we need to keep the systems-intern challenge, or can we remove that directory? Or perhaps convert it to a L0 in the regular systems challenge.  I worry this 2nd copy will continue to fall out of date.
2. During my conversion, I reformatted the engineering levels from a table to headers (view it [here](https://github.com/gravitational/careers/blob/walt/latex-begone/levels/systems-engineer.md)).  This is good for linking but bad for legibility.  Should I put it back in a table (a la the [SRE levels](https://github.com/gravitational/careers/tree/main/challenges/cloud#levels-1))?
3. I moved `levels.pdf` to `levels/systems-engineer.md` in anticipation of future split out.  We already have a separate matrix for SRE levels and I know Pierre and Zac were working on one for fullstack/frontend.  I imagine `levels/` might function akin to `challenges/` or `jobs/` shortly, where we have a separate file for each engineering track in the directory.  Yea or nay?

### CODE REVIEW

**Review by russjones — CHANGES_REQUESTED** [review]
> Do we need to keep the systems-intern challenge

Yes, we should keep this challenge.

> During my conversion, I reformatted the engineering levels from a table to headers

Please revert these changes.

**Comment by wadells** [comment]
> > During my conversion, I reformatted the engineering levels from a table to headers
> 
> Please revert these changes.

Done in 2b74eb01e59de34436ac68a184766d72697aab60.

I also made a [version reflected over the  y=x](https://github.com/gravitational/careers/pull/65/commits/2b74eb01e59de34436ac68a184766d72697aab60).  I think this reads better because:

1) Horizontal space is more limited than vertical in the markdown layout.  We have more skills (7) than levels (6), thus having skills on the vertical axis capitalizes on the vertical flexibility.
2) The column width in the is determined by the header.  "L1"-"L6" are more consistent width than "Data Structures & algorithms" vs "Security".

Let me know if you'd rather I include the reflected version in this PR.

**Comment by russjones** [comment]
Please revert the levels changes in favor of https://github.com/gravitational/careers/pull/68.

**Comment by wadells** [comment]
> Please revert the levels changes in favor of #68.

I'm not sure this PR is worth moving forward with if we keep using latex for levels as proposed in #68.  The makefile & gitignore removed herein will still be needed.  I'll close this and reopen a new PR that only converts the system-intern challenge.

**Pull request closed without merging**
